version: '3.8'
services:
  client:
    build:
      context: ./clientProtocol
      dockerfile: Dockerfile
    container_name: 'client_container'
    networks:
      bridge:
        ipv4_address: 172.10.1.3
    depends_on:
      - server
  server:
    build:
      context: ./serverProtocol
      dockerfile: Dockerfile
    container_name: 'server_container'
    networks:
      bridge:
        ipv4_address: 172.10.1.2
networks:
  bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.1.0/16
          gateway: 172.10.1.1